FROM nginx:latest

LABEL org.opencontainers.image.authors=duminda79@gmail.com
LABEL org.opencontainers.image.title="csi-test"
LABEL org.opencontainers.image.licenses=csi

WORKDIR /var/
COPY index.html /usr/share/nginx/html/
EXPOSE 80
